Making changes suggested by our docs writers to elasticsearch and mysql sed
redhat-developer/service-endpoint-definition pull request #10
Opened 2022-05-02 05:32 UTC by Kartikey-star

Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

2022-05-05 15:48 UTC, Srivaralakshmi requested changes
@Kartikey-star Left some suggestions. PTAL. Thanks!

2022-05-05 15:48 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +This helm chart defines a Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to
```suggestion
This Helm chart defines an Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authenticate. The following values are to be customized while installing the SED chart:
```
Suggestion: The H in Helm is always in capitals. Global comment. Please change in all such instances.

2022-05-05 15:48 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Elasticsearch SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```
Suggestion: Apply the comment to MySQL SED content also.

2022-05-06 10:15 UTC, Kartikey-star commented on seds/elasticsearch-sed/README.md
> +This helm chart defines a Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to
Made the change

2022-05-06 10:15 UTC, Kartikey-star commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
Made the change

2022-05-09 09:57 UTC, Srivaralakshmi requested changes
@Kartikey-star Left some comments. PTAL. Thanks!

2022-05-09 09:57 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Elasticsearch SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```

2022-05-09 09:57 UTC, Srivaralakshmi commented on seds/mysql-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the MySQL SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```

2022-05-09 09:57 UTC, Srivaralakshmi commented on seds/mysql-sed/README.md
> +This Helm chart defines a MySQL Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authenti
```suggestion
This Helm chart defines a MySQL Service Endpoint Definition (SED). When the SED chart is installed, it provides the user with the opportunity to provide binding data and credentials to authenticate. The following values must be customized while installing the SED chart:
```

2022-05-09 10:00 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +This Helm chart defines an Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to
```suggestion
This Helm chart defines an Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed, it provides the user with the opportunity to provide binding data and credentials to authenticate. The following values must be customized while installing the SED chart:
```

2022-05-09 10:21 UTC, Kartikey-star commented on seds/mysql-sed/README.md
> +This Helm chart defines a MySQL Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authenti
Changes Done

2022-05-09 10:21 UTC, Kartikey-star commented on seds/elasticsearch-sed/README.md
> +This Helm chart defines an Elasticsearch Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to
Changes made

2022-05-09 11:34 UTC, Srivaralakshmi requested changes
@Kartikey-star Seems you have missed out on this comment. PTAL. Thanks!

2022-05-09 11:34 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Elasticsearch SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```

2022-05-09 11:34 UTC, Srivaralakshmi commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
Added space. Please apply this change.

2022-05-18 14:52 UTC, Kartikey-star commented on seds/elasticsearch-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification's [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
Made the change

2022-05-18 14:54 UTC, Srivaralakshmi approved these changes
@Kartikey-star Approved! Thanks for the great work!

2022-05-18 14:54 UTC, Srivaralakshmi commented
/lgtm

2022-05-19 06:58 UTC, Srivaralakshmi commented
/approve

2022-05-24 18:38 UTC, merged