Making changes suggested by our docs writers to MongoDB and redis sed
redhat-developer/service-endpoint-definition pull request #11
Opened 2022-05-02 07:19 UTC by fbm3307

Making changes suggested by our docs writers to MongoDB and redis sed

Signed-off-by: Feny Mehta <fbm3307@gmail.com>

2022-05-05 15:42 UTC, Srivaralakshmi requested changes
@fbm3307 Left some suggestions. PTAL. Thanks!

2022-05-05 15:42 UTC, Srivaralakshmi commented on seds/mongodb-sed/README.md
> +This helm chart defines a MongoDB Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authen
```suggestion
This Helm chart defines a MongoDB Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authenticate. The following values are to be customized while installing the SED chart:
```

Suggestion: The H in Helm is always in capitals. Global comment. Please change in all such instances.

2022-05-05 15:42 UTC, Srivaralakshmi commented on seds/mongodb-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the MongoDB SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```
Suggestion: Apply the comment to Redis SED content also.

2022-05-09 09:59 UTC, Srivaralakshmi requested changes
@fbm3307 Some more comments. PTAL. Thanks!

2022-05-09 09:59 UTC, Srivaralakshmi commented on seds/redis-sed/README.md
> +This helm chart defines a Redis Service Endpoint Definition (SED). When the SED chart is installed it provides the user with the opportunity to provide binding data as well as credentials to authenti
```suggestion
This helm chart defines a Redis Service Endpoint Definition (SED). When the SED chart is installed, it provides the user with the opportunity to provide binding data and credentials to authenticate. The following values must be customized while installing the SED chart:
```

2022-05-16 07:35 UTC, Srivaralakshmi requested changes
@fbm3307 PTAL. Thanks!

2022-05-16 07:35 UTC, Srivaralakshmi commented on seds/redis-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Redis SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Redis SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Binding Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```

2022-05-24 06:19 UTC, fbm3307 commented
@Srivaralakshmi done with the suggested changes PTAL

2022-05-24 11:07 UTC, Srivaralakshmi approved these changes
@fbm3307 LGTM. Thanks for the changes. Approved!

2022-05-24 11:07 UTC, Srivaralakshmi commented on seds/redis-sed/README.md
> +The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-kno
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Redis SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```
```suggestion
The SED chart will render a secret with the binding data. This secret is compliant with the Service Binding Specification’s [Well Known Secret Entries](https://github.com/servicebinding/spec#well-known-secret-entries). Therefore, the secret rendered by the Redis SED chart is a bindable service endpoint that can be projected to workloads using the Service Binding specification’s [Binding Direct Secret Reference](https://github.com/servicebinding/spec#direct-secret-reference).
```

2022-05-24 11:07 UTC, Srivaralakshmi commented
/lgtm

2022-05-24 11:07 UTC, Srivaralakshmi commented
/approved

2022-05-24 18:37 UTC, merged